### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by LilaMJordan** [dryuen/ist5313-f19-group3#2]
Group two feedback: The names of the live links don't match up with the image of the navigation bar on the side, made it a little more difficult to follow which page was which, but still worked. We noticed that audio tag is on each page. Is each page going to have audio? The layout of the page is clean and easy to follow. We really liked your bottom navigation bar.

**Comment by gdg308** [comment]
Removed audio from pages that did not need audio. Thank you!
